function showHideIbgBeta(){$.ajax({url:"https://download2.interactivebrokers.com/installers/ibgateway/main.json",dataType:"jsonp",jsonpCallback:"ibgateway_callback",success:function(a){a=a.hideBeta||"";""!=a&&"true"==a&&$("li.ibgBeta").hide()}})}
function getStableIbgData(){var a="N/A";$.ajax({url:"https://download2.interactivebrokers.com/installers/ibgateway/stable-standalone/version.json",dataType:"jsonp",jsonpCallback:"ibgatewaystable_callback",success:function(b){a=b.buildVersion;$("span.stableIbgBuildVersion").text(a)}})}
function getLatestIbgData(){var a="N/A";$.ajax({url:"https://download2.interactivebrokers.com/installers/ibgateway/latest-standalone/version.json",dataType:"jsonp",jsonpCallback:"ibgatewaylatest_callback",success:function(b){a=b.buildVersion;$("span.latestIbgBuildVersion").text(a)}})}
function getStableTwsData(){var a="N/A";$.ajax({url:"https://download2.interactivebrokers.com/installers/tws/stable/version.json",dataType:"jsonp",jsonpCallback:"twsstableupdatable_callback",success:function(b){a=b.buildVersion;$("span.stableBuildVersion").text(a)}})}
function getLatestTwsData(){var a="N/A";$.ajax({url:"https://download2.interactivebrokers.com/installers/tws/latest/version.json",dataType:"jsonp",jsonpCallback:"twslatestupdatable_callback",success:function(b){a=b.buildVersion;$("span.latestBuildVersion").text(a)}})}
function getLatestStandaloneTwsData(){var a="N/A";$.ajax({url:"https://download2.interactivebrokers.com/installers/tws/latest-standalone/version.json",dataType:"jsonp",jsonpCallback:"twslatest_callback",success:function(b){a=b.buildVersion;$("span.latestStandaloneBuildVersion").text(a)}})}
function getStableStandaloneTwsData(){var a="N/A";$.ajax({url:"https://download2.interactivebrokers.com/installers/tws/stable-standalone/version.json",dataType:"jsonp",jsonpCallback:"twsstable_callback",success:function(b){a=b.buildVersion;$("span.stableStandaloneBuildVersion").text(a)}})}
function getLatestWBTwsData(a){var b="N/A";wbidl=a.toLowerCase();$.ajax({url:"https://download2.interactivebrokers.com/installers/"+wbidl+"/"+wbidl+"/version.json",dataType:"jsonp",jsonpCallback:wbidl+"_callback",success:function(c){b=c.buildVersion;$("span."+a+"latestStandaloneBuildVersion").text(b)}})}
function getAlphaTwsData(){var a="N/A";$.ajax({url:"https://download2.interactivebrokers.com/installers/tws/alpha/version.json",dataType:"jsonp",jsonpCallback:"twsalphaupdatable_callback",success:function(b){a=b.buildVersion;"none"==a?$("div#alpha-none").show():($("span.alphaBuildVersion").text(a),$("div#alpha-vers").show())}})}
function getBetaTwsData(){var a="N/A";$.ajax({url:"https://download2.interactivebrokers.com/installers/tws/beta/version.json",dataType:"jsonp",jsonpCallback:"twsbetaupdatable_callback",success:function(b){a=b.buildVersion;$("span.betaBuildVersion").text(a)}})}
function getNightlyTwsData(){var a="N/A";$.ajax({url:"https://download2.interactivebrokers.com/installers/tws/nightly/version.json",dataType:"jsonp",jsonpCallback:"twsnightlyupdatable_callback",success:function(b){a=b.buildVersion;$("span.nightlyBuildVersion").text(a)}})}$(function(){getAlphaTwsData();getBetaTwsData();getLatestTwsData();getLatestStandaloneTwsData();getStableStandaloneTwsData();getStableTwsData()});
